package br.com.caelum.brutal.model;

public enum EventType {
	
	QUESTION_UPVOTE, QUESTION_DOWNVOTE, ANSWER_UPVOTE, ANSWER_DOWNVOTE, 
	COMMENT_UPVOTE, EDIT_APPROVED, CREATED_ANSWER, CREATED_QUESTION
	

}
